vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO KomputeProject/kompute
    REF 342af81a671099ff590effc30af18551db063917  # Used this SHA in the python test
    SHA512 2F3B83DC3455A1BCBE5D8DD407FD81C3BC2F23CCEA6A6F76626F8E36F541D230F88CDAFFC6B34A0DD34586B5DE6098D6779DC425807152577D52F8D9CF0EBEF4
    HEAD_REF master
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DKOMPUTE_OPT_BUILD_TESTS=OFF
        -DKOMPUTE_OPT_CODE_COVERAGE=OFF
        -DKOMPUTE_OPT_BUILD_DOCS=OFF
        -DKOMPUTE_OPT_INSTALL=ON
        -DKOMPUTE_OPT_BUILD_PYTHON=OFF
        -DKOMPUTE_OPT_LOG_LEVEL="Default"
        -DKOMPUTE_OPT_USE_SPDLOG=OFF
        -DKOMPUTE_OPT_ANDROID_BUILD=OFF
        -DKOMPUTE_OPT_DISABLE_VK_DEBUG_LAYERS=OFF
        -DKOMPUTE_OPT_BUILD_SHADERS=OFF              # Requires glslangValidator, i.e. glslang[tools]
        -DKOMPUTE_OPT_USE_BUILT_IN_SPDLOG=OFF
        -DKOMPUTE_OPT_SPDLOG_ASYNC_MODE=OFF
        -DKOMPUTE_OPT_USE_BUILT_IN_FMT=OFF
        -DKOMPUTE_OPT_USE_BUILT_IN_GOOGLE_TEST=OFF
        -DKOMPUTE_OPT_USE_BUILT_IN_PYBIND11=OFF
        -DKOMPUTE_OPT_USE_BUILT_IN_VULKAN_HEADER=OFF
        -DVulkan_GLSLC_EXECUTABLE="${CURRENT_HOST_INSTALLED_DIR}/tools/shaderc/glslc${VCPKG_HOST_EXECUTABLE_SUFFIX}"
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/kompute)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
