#version 430

#extension GL_EXT_scalar_block_layout : require
#extension GL_ARB_shading_language_include : enable

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer ActivePixels {
    uvec2 activePixels[];
};

layout(std430, binding = 1) readonly buffer ActiveCount {
    uint activeCount;
};

layout(std430, binding = 2) readonly buffer Positions {
    vec2 positions[];
};

layout(std430, binding = 3) readonly buffer BoundsInterface { vec2 Bounds[]; };

layout(rgba32f, binding = 4) writeonly uniform image2D Fields;
layout(scalar, binding = 5) uniform FieldPushConstants {
    uint num_points;
    vec2 imageSize;
    float support;  
} pc;

#define TILE_SIZE 256
shared vec2 sharedPositions[TILE_SIZE];

void main() {
  // pixelIndex - the index to the output texture pixel coordinates
    uint pixelIndex = gl_GlobalInvocationID.x;
    if (pixelIndex >= activeCount) return;

    vec2 min_bounds = Bounds[0];
    vec2 max_bounds = Bounds[1];
    vec2 range = max_bounds - min_bounds;
    uint tid = gl_LocalInvocationIndex;
    
    uvec2 pixelCoord = activePixels[pixelIndex];
    vec2 pixel_pos = (((vec2(pixelCoord.x, pixelCoord.y) + vec2(0.5)) / pc.imageSize) * range) + min_bounds;
    
    vec3 accumulator = vec3(0);
    // Tile loop with shared memory
    // The tile loop is designed to share access latency to the position SBO
    uint numTiles = (pc.num_points + TILE_SIZE - 1) / TILE_SIZE;

    for (uint tileIdx = 0; tileIdx < numTiles; tileIdx++) {
      uint pointBase = tileIdx * TILE_SIZE;
      uint loadIdx = pointBase + tid;
      
      if (loadIdx < pc.num_points) {
          sharedPositions[tid] = positions[loadIdx];
      }
      memoryBarrierShared();
      barrier();
      
      uint tileEnd = min(TILE_SIZE, pc.num_points - pointBase);

      for (uint i = 0; i < tileEnd; i++) {
          vec2 t = pixel_pos - sharedPositions[i];
          float eucl_sqrd = dot(t, t);
          float tstud = 1.0 / (1.0 + eucl_sqrd);
          float tstud2 = tstud * tstud;
          accumulator += vec3(tstud, tstud2 * t.x, tstud2 * t.y);
      }
      memoryBarrierShared();
      barrier();
    }
    
    imageStore(Fields, ivec2(pixelCoord), vec4(accumulator, 0));
}