#version 450
layout(local_size_x = 1) in;

layout(std430, binding = 0) coherent buffer AtomicCounter {
    uint atomicCounter;
};

layout(std430, binding = 1) writeonly buffer IndirectDispatch {
    uint groupCountX;
    uint groupCountY;
    uint groupCountZ;
};

void main() {
    uint workgroups = (atomicCounter + 255u) / 256u;
    groupCountX = workgroups;
    groupCountY = 1;
    groupCountZ = 1;
}