#version 430

#extension GL_EXT_scalar_block_layout : require
#extension GL_ARB_shading_language_include : enable

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer ActivePixels {
    uvec2 activePixels[];
};

layout(std430, binding = 1) readonly buffer ActiveCount {
    uint activeCount;
};

layout(std430, binding = 2) readonly buffer Positions {
    vec2 positions[];
};

layout(std430, binding = 3) readonly buffer BoundsInterface { vec2 Bounds[]; };

layout(rgba32f, binding = 4) writeonly uniform image2D Fields;
layout(scalar, binding = 5) uniform FieldPushConstants {
    uint num_points;
    vec2 imageSize;
    float support;  
} pc;

void main() {
    uint pixelIndex = gl_GlobalInvocationID.x;
    vec2 min_bounds = Bounds[0];
    vec2 max_bounds = Bounds[1];
    vec2 range = max_bounds - min_bounds;

    if (pixelIndex >= activeCount) return;
    
    uvec2 pixelCoord = activePixels[pixelIndex];
    vec2 pixel_pos = (((vec2(pixelCoord.x, pixelCoord.y) + vec2(0.5)) / pc.imageSize) * range) + min_bounds;
    
    vec3 value = vec3(0);
    for (uint i = 0; i < positions.length(); i++) {
        vec2 t = pixel_pos - positions[i];
        float eucl_sqrd = dot(t, t);
        float tstud = 1.0 / (1.0 + eucl_sqrd);
        float tstud2 = tstud * tstud;
        value += vec3(tstud, tstud2 * t.x, tstud2 * t.y);
    }
    
    imageStore(Fields, ivec2(pixelCoord), vec4(value, 0));
}